// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZenithApp.Data;

#nullable disable

namespace ZenithApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523215642_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZenithApp.Models.Alimento", b =>
                {
                    b.Property<int>("IdAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAlimento"));

                    b.Property<int?>("Calorias")
                        .HasColumnType("int");

                    b.Property<int?>("Carboidratos")
                        .HasColumnType("int");

                    b.Property<int?>("IdSistema")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Proteinas")
                        .HasColumnType("int");

                    b.HasKey("IdAlimento");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("ZenithApp.Models.Atleta", b =>
                {
                    b.Property<int>("IdAtleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAtleta"));

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Biotipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("CompCorporal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("IdLogin")
                        .HasColumnType("int");

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<decimal?>("Largura")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdAtleta");

                    b.HasIndex("IdLogin")
                        .IsUnique();

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("ZenithApp.Models.Login", b =>
                {
                    b.Property<int>("IdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLogin"));

                    b.Property<string>("NivelAcesso")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdLogin");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ZenithApp.Models.RegistroPerformance", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<int?>("Cardio")
                        .HasColumnType("int");

                    b.Property<int?>("Forca")
                        .HasColumnType("int");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int?>("Velocidade")
                        .HasColumnType("int");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdAtleta");

                    b.ToTable("RegistrosPerformance");
                });

            modelBuilder.Entity("ZenithApp.Models.Treinador", b =>
                {
                    b.Property<int>("IdTreinador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTreinador"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IdLogin")
                        .HasColumnType("int");

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdTreinador");

                    b.HasIndex("IdLogin")
                        .IsUnique();

                    b.ToTable("Treinadores");
                });

            modelBuilder.Entity("ZenithApp.Models.TreinadorAlimento", b =>
                {
                    b.Property<int>("IdTreinador")
                        .HasColumnType("int");

                    b.Property<int>("IdAlimento")
                        .HasColumnType("int");

                    b.HasKey("IdTreinador", "IdAlimento");

                    b.HasIndex("IdAlimento");

                    b.ToTable("TreinadorAlimentos");
                });

            modelBuilder.Entity("ZenithApp.Models.TreinadorAtleta", b =>
                {
                    b.Property<int>("IdTreinador")
                        .HasColumnType("int");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.HasKey("IdTreinador", "IdAtleta");

                    b.HasIndex("IdAtleta");

                    b.ToTable("TreinadorAtletas");
                });

            modelBuilder.Entity("ZenithApp.Models.Treino", b =>
                {
                    b.Property<int>("IdTreino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTreino"));

                    b.Property<int?>("Carga")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataTreino")
                        .HasColumnType("date");

                    b.Property<int?>("Duracao")
                        .HasColumnType("int");

                    b.Property<int?>("IdSistema")
                        .HasColumnType("int");

                    b.Property<int?>("IdTreinador")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTreino");

                    b.HasIndex("IdTreinador");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("ZenithApp.Models.Atleta", b =>
                {
                    b.HasOne("ZenithApp.Models.Login", "Login")
                        .WithOne("Atleta")
                        .HasForeignKey("ZenithApp.Models.Atleta", "IdLogin");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("ZenithApp.Models.RegistroPerformance", b =>
                {
                    b.HasOne("ZenithApp.Models.Atleta", "Atleta")
                        .WithMany("Performances")
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");
                });

            modelBuilder.Entity("ZenithApp.Models.Treinador", b =>
                {
                    b.HasOne("ZenithApp.Models.Login", "Login")
                        .WithOne("Treinador")
                        .HasForeignKey("ZenithApp.Models.Treinador", "IdLogin");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("ZenithApp.Models.TreinadorAlimento", b =>
                {
                    b.HasOne("ZenithApp.Models.Alimento", "Alimento")
                        .WithMany("TreinadorAlimentos")
                        .HasForeignKey("IdAlimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenithApp.Models.Treinador", "Treinador")
                        .WithMany("TreinadorAlimentos")
                        .HasForeignKey("IdTreinador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("ZenithApp.Models.TreinadorAtleta", b =>
                {
                    b.HasOne("ZenithApp.Models.Atleta", "Atleta")
                        .WithMany("TreinadorAtletas")
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenithApp.Models.Treinador", "Treinador")
                        .WithMany("TreinadorAtletas")
                        .HasForeignKey("IdTreinador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("ZenithApp.Models.Treino", b =>
                {
                    b.HasOne("ZenithApp.Models.Treinador", "Treinador")
                        .WithMany("Treinos")
                        .HasForeignKey("IdTreinador");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("ZenithApp.Models.Alimento", b =>
                {
                    b.Navigation("TreinadorAlimentos");
                });

            modelBuilder.Entity("ZenithApp.Models.Atleta", b =>
                {
                    b.Navigation("Performances");

                    b.Navigation("TreinadorAtletas");
                });

            modelBuilder.Entity("ZenithApp.Models.Login", b =>
                {
                    b.Navigation("Atleta");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("ZenithApp.Models.Treinador", b =>
                {
                    b.Navigation("TreinadorAlimentos");

                    b.Navigation("TreinadorAtletas");

                    b.Navigation("Treinos");
                });
#pragma warning restore 612, 618
        }
    }
}
