// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZenithApp.Data;

#nullable disable

namespace ZenithApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZenithApp.Models.Atleta", b =>
                {
                    b.Property<int>("IdAtleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAtleta"));

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int?>("IdLogin")
                        .HasColumnType("int");

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<decimal?>("Largura")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdAtleta");

                    b.HasIndex("IdLogin")
                        .IsUnique();

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("ZenithApp.Models.ConviteTreinador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("IdTreinador")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdTreinador");

                    b.ToTable("ConvitesTreinador");
                });

            modelBuilder.Entity("ZenithApp.Models.Exercicio", b =>
                {
                    b.Property<int>("IdExercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdExercicio"));

                    b.Property<int>("IdTreino")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("IdExercicio");

                    b.HasIndex("IdTreino");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("ZenithApp.Models.Login", b =>
                {
                    b.Property<int>("IdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLogin"));

                    b.Property<string>("NivelAcesso")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdLogin");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ZenithApp.Models.MetaSemana", b =>
                {
                    b.Property<int>("IdMeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMeta"));

                    b.Property<bool>("Concluida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("IdTreinador")
                        .HasColumnType("int");

                    b.HasKey("IdMeta");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdTreinador");

                    b.ToTable("MetasSemana");
                });

            modelBuilder.Entity("ZenithApp.Models.Treinador", b =>
                {
                    b.Property<int>("IdTreinador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTreinador"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IdLogin")
                        .HasColumnType("int");

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdTreinador");

                    b.HasIndex("IdLogin")
                        .IsUnique();

                    b.ToTable("Treinadores");
                });

            modelBuilder.Entity("ZenithApp.Models.TreinadorAtleta", b =>
                {
                    b.Property<int>("IdTreinador")
                        .HasColumnType("int");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.HasKey("IdTreinador", "IdAtleta");

                    b.HasIndex("IdAtleta");

                    b.ToTable("TreinadorAtletas");
                });

            modelBuilder.Entity("ZenithApp.Models.Treino", b =>
                {
                    b.Property<int>("IdTreino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTreino"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("IdTreinador")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.HasKey("IdTreino");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdTreinador");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("ZenithApp.Models.Atleta", b =>
                {
                    b.HasOne("ZenithApp.Models.Login", "Login")
                        .WithOne("Atleta")
                        .HasForeignKey("ZenithApp.Models.Atleta", "IdLogin");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("ZenithApp.Models.ConviteTreinador", b =>
                {
                    b.HasOne("ZenithApp.Models.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenithApp.Models.Treinador", "Treinador")
                        .WithMany()
                        .HasForeignKey("IdTreinador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("ZenithApp.Models.Exercicio", b =>
                {
                    b.HasOne("ZenithApp.Models.Treino", "Treino")
                        .WithMany("Exercicios")
                        .HasForeignKey("IdTreino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("ZenithApp.Models.MetaSemana", b =>
                {
                    b.HasOne("ZenithApp.Models.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenithApp.Models.Treinador", "Treinador")
                        .WithMany()
                        .HasForeignKey("IdTreinador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("ZenithApp.Models.Treinador", b =>
                {
                    b.HasOne("ZenithApp.Models.Login", "Login")
                        .WithOne("Treinador")
                        .HasForeignKey("ZenithApp.Models.Treinador", "IdLogin");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("ZenithApp.Models.TreinadorAtleta", b =>
                {
                    b.HasOne("ZenithApp.Models.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenithApp.Models.Treinador", "Treinador")
                        .WithMany()
                        .HasForeignKey("IdTreinador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("ZenithApp.Models.Treino", b =>
                {
                    b.HasOne("ZenithApp.Models.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenithApp.Models.Treinador", "Treinador")
                        .WithMany()
                        .HasForeignKey("IdTreinador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("ZenithApp.Models.Login", b =>
                {
                    b.Navigation("Atleta");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("ZenithApp.Models.Treino", b =>
                {
                    b.Navigation("Exercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
